# -*- coding: utf-8 -*-
"""helloworld_st.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gqrr5WdEuD5_oIqRmyoExL_PonArRGNg
"""

import streamlit as st
import xgboost as xgb 
import pandas as pd

model = xgb.Booster()
model.load_model("C:/Users/Idris/0 Python/MSJData/ViewIT/dxb_re_predictions/xgbmodelBus.xgb")
input_data = pd.read_excel('C:/Users/Idris/0 Python/MSJData/ViewIT/dxb_re_predictions/inputdata.xlsx')
training_data = pd.read_csv('C:/Users/Idris/0 Python/MSJData/ViewIT/dxb_re_predictions/ml_inputBus.csv')


st.write(""" 
# Price prediction for the Property in Business Bay


""")

styled_table = (
    f'<style>'
    f'table {{ width: 300px; margin-left: -20px; padding-left: 0; }}'  # Set the desired width and reduce the left margin and padding
    f'table th, table td {{ word-wrap: break-word; }}'  # Enable word wrapping
    f'</style>'
    f'{input_data.to_html()}'
)
st.markdown(styled_table, unsafe_allow_html=True)


#st.dataframe(input_data)

dict = input_data.to_dict(orient='list')
new_dict = {key: value[0] for key, value in dict.items()}
mod_dict = {f'{key}_{value}' if isinstance(value, str) else key: (value if isinstance(value, (int, float)) else 1) for key, value in new_dict.items()}
training_columns = training_data.columns
new_data_df = pd.DataFrame(columns=training_columns)
new_data_df = new_data_df.append(mod_dict, ignore_index = True)
new_data_df = new_data_df.fillna(0)


ml_input = new_data_df.iloc[:,1:]
ml_input = ml_input.values

ml_input =  xgb.DMatrix(ml_input)

prediction = model.predict(ml_input)

st.write("The Predicted value of the Property:", prediction)